/*
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/devicetree.h>

#include <hc32_ll_icg.h>

#define HC32_SWDT_NODE DT_NODELABEL(swdt0)

#undef ICG_REG_CFG0_CONST

#define HC32_ICG_WDT_CONFIG (ICG_WDT_RST_STOP | ICG_WDT_EXP_TYPE_RST | \
     ICG_WDT_CNT_PERIOD65536 | ICG_WDT_CLK_DIV8192 | \
     ICG_WDT_RANGE_0TO100PCT | ICG_WDT_LPM_CNT_STOP)

#if DT_PROP(HC32_SWDT_NODE, clock_divider) == 1
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV1
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 16
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV16
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 32
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV32
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 64
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV64
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 128
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV128
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 256
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV256
#elif DT_PROP(HC32_SWDT_NODE, clock_divider) == 2048
#define HC32_ICG_SWDT_CLK_DIV ICG_SWDT_CLK_DIV2048
#else
#error "Unsupported SWDT clock divider"
#endif

#if DT_PROP(HC32_SWDT_NODE, counter_cycles) == 256
#define HC32_ICG_SWDT_CNT_PERIOD ICG_SWDT_CNT_PERIOD256
#elif DT_PROP(HC32_SWDT_NODE, counter_cycles) == 4096
#define HC32_ICG_SWDT_CNT_PERIOD ICG_SWDT_CNT_PERIOD4096
#elif DT_PROP(HC32_SWDT_NODE, counter_cycles) == 16384
#define HC32_ICG_SWDT_CNT_PERIOD ICG_SWDT_CNT_PERIOD16384
#elif DT_PROP(HC32_SWDT_NODE, counter_cycles) == 65536
#define HC32_ICG_SWDT_CNT_PERIOD ICG_SWDT_CNT_PERIOD65536
#else
#error "Unsupported SWDT counter period"
#endif

#define HC32_ICG_SWDT_EXCEPTION (DT_PROP(HC32_SWDT_NODE, reset_on_timeout) ? \
 ICG_SWDT_EXP_TYPE_RST : ICG_SWDT_EXP_TYPE_INT)
#define HC32_ICG_SWDT_LPM       (DT_PROP(HC32_SWDT_NODE, run_in_sleep) ? \
 ICG_SWDT_LPM_CNT_CONT : ICG_SWDT_LPM_CNT_STOP)
#define HC32_ICG_SWDT_CONFIG    (ICG_SWDT_RST_STOP | HC32_ICG_SWDT_EXCEPTION | \
 HC32_ICG_SWDT_CNT_PERIOD | HC32_ICG_SWDT_CLK_DIV | \
 ICG_SWDT_RANGE_0TO100PCT | HC32_ICG_SWDT_LPM)

#define ICG_REG_CFG0_CONST (HC32_ICG_WDT_CONFIG | HC32_ICG_SWDT_CONFIG | 0xE000E000UL)

/*
 * F4A0 ICG has 24 entries: CFG0, CFG1, resv, CFG3, then 20 reserved.
 * CFG1/CFG3 use the DDL-provided defaults (BOR/HRC/FLASH_PROTECT).
 */
__USED const uint32_t u32ICGValue[] __attribute__((section(".icg_sec"))) = {
ICG_REG_CFG0_CONST,
ICG_REG_CFG1_CONST,
ICG_REG_RESV_CONST,
ICG_REG_CFG3_CONST,
ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST,
ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST,
ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST,
ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST,
ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST, ICG_REG_RESV_CONST,
};
