# SPDX-License-Identifier: Apache-2.0

CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y

# HC32F460 specific
CONFIG_ARM_MPU=n
CONFIG_HW_STACK_PROTECTION=n
CONFIG_DYNAMIC_INTERRUPTS=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_PM=y
CONFIG_SYSTEM_TIMER_LPM_COMPANION_HOOKS=y

# UART interrupt mode (required by shell)
CONFIG_UART_HC32_INTERRUPT=y

# Input subsystem for gpio-keys button
CONFIG_INPUT=y

# Zephyr Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
